#!/bin/bash

#

# chkconfig:   2345 90 10                // 否则 chkconfig 无效

# description:  Redis is a persistent key-value database          //redis数据库描述

# Simple Redis init.d script conceived to work on Linux systems

# as it does use of the /proc filesystem.



REDISPORT=6379

EXEC=/usr/local/redis3.2.8/bin/redis-server

CLIEXEC=/usr/local/redis3.2.8/bin/redis-cli



PIDFILE=/var/run/redis_${REDISPORT}.pid

CONF="/usr/local/redis3.2.8/etc/redis.conf"



case "$1" in

    start)

        if [ -f $PIDFILE ]

        then

                echo "$PIDFILE exists, process is already running or crashed"

        else

                echo "Starting Redis server..."

                $EXEC $CONF

        fi

        ;;

    stop)

        if [ ! -f $PIDFILE ]

        then

                echo "$PIDFILE does not exist, process is not running"

        else

                PID=$(cat $PIDFILE)

                echo "Stopping ..."

                $CLIEXEC -p $REDISPORT shutdown

                while [ -x /proc/${PID} ]

                do

                    echo "Waiting for Redis to shutdown ..."

                    sleep 1

                done

                echo "Redis stopped"

        fi

        ;;

    *)

        echo "Please use start or stop as first argument"

        ;;

esac